import { Project } from "../types";
import { subDays } from "date-fns";

export const initialProjects: Project[] = [
  {
    id: "1",
    clientName: "Jean-Pierre Schmit",
    address: "24 Rue de la Gare, L-1234 Luxembourg",
    kwp: 8.5,
    value: 18500,
    status: "quote",
    createdAt: subDays(new Date(), 14),
    daysInStage: 14,
    lastContactDaysAgo: 3,
    phone: "+352 691 123 456",
    nextAction: "Send quote PDF",
    notes: ["Interested in battery storage", "Roof faces South-West"],
  },
  {
    id: "2",
    clientName: "Maria Ferreira",
    address: "12 Avenue du Rock'n'Roll, L-4361 Esch-sur-Alzette",
    kwp: 12.0,
    value: 26000,
    status: "creos",
    createdAt: subDays(new Date(), 30),
    daysInStage: 22,
    lastContactDaysAgo: 8,
    phone: "+352 621 987 654",
    nextAction: "Send CREOS documents",
    notes: ["Waiting for CREOS approval", "Need to double check inverter stock"],
  },
  {
    id: "3",
    clientName: "Marc Weber",
    address: "8 Route d'Arlon, L-8008 Strassen",
    kwp: 6.2,
    value: 14500,
    status: "lead",
    createdAt: subDays(new Date(), 2),
    daysInStage: 2,
    lastContactDaysAgo: 2,
    phone: "+352 661 555 123",
    nextAction: "Call client",
    notes: ["Lead from website", "Asking about Klimabonus"],
  },
  {
    id: "4",
    clientName: "Sophie Wagner",
    address: "5 Rue du Parc, L-3542 Dudelange",
    kwp: 15.5,
    value: 32000,
    status: "visit",
    createdAt: subDays(new Date(), 8),
    daysInStage: 5,
    lastContactDaysAgo: 5,
    phone: "+352 691 444 777",
    nextAction: "Schedule site visit",
    notes: ["Large roof area", "Prefers black panels"],
  },
  {
    id: "5",
    clientName: "Antonio Silva",
    address: "18 Rue de la Libération, L-4601 Differdange",
    kwp: 5.0,
    value: 11000,
    status: "installation",
    createdAt: subDays(new Date(), 45),
    daysInStage: 4,
    lastContactDaysAgo: 1,
    phone: "+352 621 222 333",
    nextAction: "Plan installation date",
    notes: ["Installation scheduled for next week", "Scaffolding required"],
  },
  {
    id: "6",
    clientName: "Lucie Hoffman",
    address: "33 Grand-Rue, L-9050 Ettelbruck",
    kwp: 9.8,
    value: 21500,
    status: "completed",
    createdAt: subDays(new Date(), 55),
    daysInStage: 10,
    lastContactDaysAgo: 15,
    phone: "+352 661 888 999",
    nextAction: "Close project",
    notes: ["Project completed successfully", "Client very happy"],
  },
  {
    id: "7",
    clientName: "Pierre Dubois",
    address: "7 Rue des Roses, L-8251 Mamer",
    kwp: 7.5,
    value: 16800,
    status: "quote",
    createdAt: subDays(new Date(), 10),
    daysInStage: 3,
    lastContactDaysAgo: 12, // Needs follow up
    phone: "+352 691 111 222",
    nextAction: "Call client",
    notes: ["Sent quote via email", "No response yet"],
  },
  {
    id: "8",
    clientName: "Nadine Klein",
    address: "14 Route de Luxembourg, L-7240 Bereldange",
    kwp: 10.5,
    value: 23000,
    status: "lead",
    createdAt: subDays(new Date(), 1),
    daysInStage: 1,
    lastContactDaysAgo: 1,
    phone: "+352 621 333 444",
    nextAction: "Call client",
    notes: ["Referral from Jean-Pierre", "Has an electric car"],
  },
  {
    id: "9",
    clientName: "Carlos Mendes",
    address: "21 Rue de l'Alzette, L-4011 Esch-sur-Alzette",
    kwp: 4.5,
    value: 10500,
    status: "visit",
    createdAt: subDays(new Date(), 12),
    daysInStage: 8,
    lastContactDaysAgo: 6,
    phone: "+352 661 666 777",
    nextAction: "Schedule site visit",
    notes: ["Difficult access to roof", "Needs detailed measurement"],
  },
  {
    id: "10",
    clientName: "Isabelle Thill",
    address: "9 Rue du Cimetière, L-8018 Strassen",
    kwp: 13.2,
    value: 28500,
    status: "creos",
    createdAt: subDays(new Date(), 25),
    daysInStage: 20, // Approaching warning
    lastContactDaysAgo: 4,
    phone: "+352 691 999 000",
    nextAction: "Send CREOS documents",
    notes: ["Submitted to CREOS", "Waiting for meter change"],
  },
  {
    id: "11",
    clientName: "Tom Becker",
    address: "2 Rue de la Montagne, L-6470 Echternach",
    kwp: 6.8,
    value: 15200,
    status: "installation",
    createdAt: subDays(new Date(), 35),
    daysInStage: 12,
    lastContactDaysAgo: 2,
    phone: "+352 621 000 111",
    nextAction: "Plan installation date",
    notes: ["Panels delivered", "Waiting for inverter"],
  },
  {
    id: "12",
    clientName: "Sarah Muller",
    address: "11 Rue de la Forêt, L-7341 Heisdorf",
    kwp: 11.0,
    value: 24000,
    status: "quote",
    createdAt: subDays(new Date(), 18),
    daysInStage: 16, // Stuck in quote
    lastContactDaysAgo: 9, // Needs follow up
    phone: "+352 661 222 555",
    nextAction: "Request deposit",
    notes: ["Quote approved verbally", "Need signed contract"],
  },
];
