import { Project } from "../types";
import { subDays, addDays } from "date-fns";

/** Builds stageEnteredAt / lastContactAt from the static day offsets in mock data */
function ts(daysAgo: number): string {
  return subDays(new Date(), daysAgo).toISOString();
}

export const initialProjects: Project[] = [
  {
    id: "1",
    clientName: "Jean-Pierre Schmit",
    address: "14 Rue de la Libération, L-3960 Ehlange",
    kwp: 8.5,
    value: 18900,
    status: "quote",
    createdAt: subDays(new Date(), 14),
    daysInStage: 14,
    lastContactDaysAgo: 3,
    phone: "+352 691 123 456",
    nextAction: "Send quote PDF",
    notes: [
      "Intéressé par le stockage batterie — à intégrer au devis (10 kWh)",
      "Toit orienté Sud, inclinaison 35° · ombrage partiel cheminée côté Est — ombres à vérifier en visite",
      "Dossier KlimaBonus à constituer après accord devis — formulaire A1 + B2 requis (Guichet.lu)",
    ],
    owner: "Sales",
    dueDate: addDays(new Date(), 5).toISOString().slice(0, 10),
    stageEnteredAt: ts(14),
    lastContactAt: ts(3),
  },
  {
    id: "2",
    clientName: "Maria Ferreira",
    address: "7 Rue Auguste Liesch, L-4370 Belvaux",
    kwp: 12.0,
    value: 26800,
    status: "creos",
    createdAt: subDays(new Date(), 32),
    daysInStage: 22,
    lastContactDaysAgo: 8,
    phone: "+352 621 987 654",
    nextAction: "Send CREOS documents",
    notes: [
      "Référence CREOS : CREOS-2025-08234 — dossier déposé le 8 janv. 2025",
      "Délai estimé retour CREOS : 4 à 6 semaines · Mise en service visée fin mars",
      "Préfinancement KlimaBonus demandé via Guichet.lu — attestation en attente",
      "Compteur Smarty à remplacer par CREOS avant raccordement — à confirmer",
    ],
    owner: "Admin",
    dueDate: addDays(new Date(), 3).toISOString().slice(0, 10),
    stageEnteredAt: ts(22),
    lastContactAt: ts(8),
  },
  {
    id: "3",
    clientName: "Marc Weber",
    address: "32 Rue de Bettembourg, L-3253 Leudelange",
    kwp: 6.2,
    value: 14200,
    status: "lead",
    createdAt: subDays(new Date(), 2),
    daysInStage: 2,
    lastContactDaysAgo: 2,
    phone: "+352 661 555 123",
    nextAction: "Call client",
    notes: [
      "Lead entrant formulaire site web · Mardi 25 fév. 14h",
      "Questions spécifiques : KlimaBonus 2026, délai installation, production hivernale",
      "Maison individuelle 2010 · toiture récente · idéal pour installation",
    ],
    owner: "Sales",
    dueDate: addDays(new Date(), 2).toISOString().slice(0, 10),
    stageEnteredAt: ts(2),
    lastContactAt: ts(2),
  },
  {
    id: "4",
    clientName: "Sophie Wagner",
    address: "5 Rue du Brill, L-3898 Foetz",
    kwp: 15.5,
    value: 33500,
    status: "visit",
    createdAt: subDays(new Date(), 8),
    daysInStage: 5,
    lastContactDaysAgo: 5,
    phone: "+352 691 444 777",
    nextAction: "Schedule site visit",
    notes: [
      "Grande surface disponible · 2 pans de toit orientés Sud et Ouest",
      "Préfère panneaux full-black pour raisons esthétiques — prévoir SunPower Maxeon",
      "Consommation élevée : voiture électrique + pompe à chaleur · dimensionnement prioritaire",
    ],
    owner: "Team",
    dueDate: addDays(new Date(), 7).toISOString().slice(0, 10),
    stageEnteredAt: ts(5),
    lastContactAt: ts(5),
  },
  {
    id: "5",
    clientName: "António Silva",
    address: "18 Rue de la Forêt, L-4831 Rodange",
    kwp: 5.0,
    value: 11500,
    status: "installation",
    createdAt: subDays(new Date(), 45),
    daysInStage: 4,
    lastContactDaysAgo: 1,
    phone: "+352 621 222 333",
    nextAction: "Plan installation date",
    notes: [
      "Installation confirmée semaine du 3 mars · Équipe : Ramos + Klein",
      "Autorisation CREOS reçue : CREOS-2025-04182 · Compteur Smarty OK",
      "Échafaudage commandé chez Scaff-Lux · livraison J-1",
      "Acompte 30% reçu (€3 450) · solde à régler à réception",
    ],
    owner: "Team",
    dueDate: addDays(new Date(), 1).toISOString().slice(0, 10),
    stageEnteredAt: ts(4),
    lastContactAt: ts(1),
  },
  {
    id: "6",
    clientName: "Lucie Hoffmann",
    address: "33 Grand-Rue, L-7411 Saeul",
    kwp: 9.8,
    value: 21800,
    status: "completed",
    createdAt: subDays(new Date(), 55),
    daysInStage: 10,
    lastContactDaysAgo: 15,
    phone: "+352 661 888 999",
    nextAction: "Close project",
    notes: [
      "Installation terminée · mise en service effectuée le 14 fév. 2025",
      "Production enregistrée portail MyEnergy.lu · onduleur Fronius connecté",
      "Client très satisfait · demande d'avis Google envoyée · attestation KlimaBonus reçue",
    ],
    owner: "Admin",
    stageEnteredAt: ts(10),
    lastContactAt: ts(15),
  },
  {
    id: "7",
    clientName: "Pierre Dubois",
    address: "7 Allée des Chênes, L-7251 Walferdange",
    kwp: 7.5,
    value: 17200,
    status: "quote",
    createdAt: subDays(new Date(), 10),
    daysInStage: 3,
    lastContactDaysAgo: 12,
    phone: "+352 691 111 222",
    nextAction: "Call client",
    notes: [
      "Devis envoyé par e-mail le 18 fév. · accusé de lecture confirmé",
      "Aucune réponse depuis 12 jours — relance urgente par WhatsApp",
      "Concurrent a déposé une offre · prix à revoir éventuellement",
    ],
    owner: "Sales",
    dueDate: addDays(new Date(), 4).toISOString().slice(0, 10),
    stageEnteredAt: ts(3),
    lastContactAt: ts(12),
  },
  {
    id: "8",
    clientName: "Nadine Klein",
    address: "21 Rue de Kirchberg, L-1858 Luxembourg",
    kwp: 10.5,
    value: 23400,
    status: "lead",
    createdAt: subDays(new Date(), 1),
    daysInStage: 1,
    lastContactDaysAgo: 1,
    phone: "+352 621 333 444",
    nextAction: "Call client",
    notes: [
      "Référence client Jean-Pierre Schmit (projet #1)",
      "Possède Tesla Model Y → dimensionnement VE prioritaire · augmenter kWp",
      "Locataire terrain propre depuis 2022 · propriétaire accord écrit nécessaire",
    ],
    owner: "Sales",
    dueDate: addDays(new Date(), 3).toISOString().slice(0, 10),
    stageEnteredAt: ts(1),
    lastContactAt: ts(1),
  },
  {
    id: "9",
    clientName: "Carlos Mendes",
    address: "9 Rue du Moulin, L-3598 Dudelange",
    kwp: 4.5,
    value: 10800,
    status: "visit",
    createdAt: subDays(new Date(), 12),
    daysInStage: 8,
    lastContactDaysAgo: 6,
    phone: "+352 661 666 777",
    nextAction: "Schedule site visit",
    notes: [
      "Accès toit via lucarne · équipement spécifique requis (nacelle ou échafaudage léger)",
      "Mesures détaillées à prendre sur place · compteur dans garage (à vérifier distance)",
      "Budget serré · explorer options financement (cofidis solaire ou prêt vert BIL)",
    ],
    owner: "Team",
    dueDate: addDays(new Date(), 10).toISOString().slice(0, 10),
    stageEnteredAt: ts(8),
    lastContactAt: ts(6),
  },
  {
    id: "10",
    clientName: "Isabelle Thill",
    address: "4 Op der Hei, L-9156 Grosbous",
    kwp: 13.2,
    value: 29100,
    status: "creos",
    createdAt: subDays(new Date(), 28),
    daysInStage: 20,
    lastContactDaysAgo: 4,
    phone: "+352 691 999 000",
    nextAction: "Send CREOS documents",
    notes: [
      "Référence CREOS : CREOS-2025-11057 — dossier soumis le 30 janv.",
      "Remplacement compteur Smarty planifié par CREOS semaine 12 — à confirmer",
      "Client relancé le 25 fév. · en attente retour CREOS · délai approche (seuil 21 jours)",
    ],
    owner: "Admin",
    dueDate: addDays(new Date(), 14).toISOString().slice(0, 10),
    stageEnteredAt: ts(20),
    lastContactAt: ts(4),
  },
  {
    id: "11",
    clientName: "Tom Becker",
    address: "2 Rue du Château, L-6480 Beaufort",
    kwp: 6.8,
    value: 15600,
    status: "raccordement",
    createdAt: subDays(new Date(), 38),
    daysInStage: 5,
    lastContactDaysAgo: 2,
    phone: "+352 621 000 111",
    nextAction: "Schedule CREOS raccordement",
    notes: [
      "Installation terminée le 24 fév. · panneaux posés, onduleur SMA raccordé AC/DC",
      "Référence CREOS raccordement : CREOS-2025-04182-RC · RDV technicien CREOS le 6 mars",
      "Client informé : présence requise lors du raccordement · clé compteur à préparer",
      "Attestation KlimaBonus batterie à soumettre après mise en service",
    ],
    owner: "Team",
    dueDate: addDays(new Date(), 6).toISOString().slice(0, 10),
    stageEnteredAt: ts(5),
    lastContactAt: ts(2),
  },
  {
    id: "12",
    clientName: "Sarah Muller",
    address: "11 Rue de la Montagne, L-5445 Schengen",
    kwp: 11.0,
    value: 24500,
    status: "quote",
    createdAt: subDays(new Date(), 18),
    daysInStage: 16,
    lastContactDaysAgo: 9,
    phone: "+352 661 222 555",
    nextAction: "Request deposit",
    notes: [
      "Devis accepté verbalement par téléphone le 12 fév.",
      "Contrat signé non retourné · relancer WhatsApp aujourd'hui",
      "Acompte 30% (€7 350) à recevoir avant planification installation",
    ],
    owner: "Sales",
    dueDate: addDays(new Date(), 7).toISOString().slice(0, 10),
    stageEnteredAt: ts(16),
    lastContactAt: ts(9),
  },
];
