/**
 * Operations console copy — Luxembourg solar installer.
 * Identidade (empresa, utilizador) vem de config/demo.ts — altere só esse ficheiro para outra empresa.
 */

import { demo } from './demo';

export const opsCopy = {
  /** Navbar & identity (fonte: config/demo.ts) */
  companyName: demo.companyName,
  consoleTagline: demo.consoleTagline,
  userName: demo.userName,
  userRole: demo.userRole,
  /** Dashboard: 30-second value */
  dashboardHeadline: 'Vos opérations en un coup d\'œil',
  dashboardSubline: 'Leads · Valeur pipeline · Gargalos CREOS · Prochaines actions. Fini Excel, WhatsApp et le papier qui vole.',
  funnelSteps: 'Lead → Devis → CREOS → Installation → Terminé',
  /** Metrics labels */
  metricLeads: 'Nouveaux leads',
  metricDevisSent: 'Devis envoyés',
  metricCreosPipeline: 'CREOS / Install',
  metricPipelineValue: 'Valeur pipeline',
  pipelineTitle: 'Pipeline — tous les projets',
  /** Mini summary above pipeline */
  summaryInPipeline: (value: string) => `${value} en pipeline`,
  summaryStuck14: (value: string) => `${value} bloqués depuis +14 jours`,
  summaryNoContact: (n: number) => n === 1 ? '1 projet sans contact' : `${n} projets sans contact`,
  /** Card: next step, owner, due date */
  cardNextStep: 'Prochaine étape',
  cardDue: 'Échéance',
  ownerLabel: 'Responsable',
  ownerSales: 'Sales',
  ownerAdmin: 'Admin',
  ownerTeam: 'Team',
  dueDateLabel: 'Date limite',
  /** Bottlenecks */
  bottleneckTitle: 'Gargalos — agir avant qu\'ils ne coûtent cher',
  creosDelayTitle: 'CREOS: dossier bloqué',
  creosDelayDesc: 'En attente depuis plus de 21 jours. Relancer CREOS ou client.',
  quoteStuckTitle: 'Devis sans réponse',
  quoteStuckDesc: 'Devis envoyé il y a plus de 2 semaines. Relancer le client.',
  followUpTitle: 'À relancer',
  followUpDesc: 'Aucun contact depuis plus de 7 jours.',
  voirProjet: 'Voir le projet',
  relancer: 'Relancer',
  moreOthers: (n: number) => `+${n} autres`,
  /** Quote page */
  quoteHeadline: 'Devis en 5 minutes',
  quoteSubline: 'Klimabonus 2026 inclus. Fourchette indicative — visite technique pour offre ferme.',
  /** Price list upload */
  quotePriceListUpload: 'Importer grille (CSV)',
  quotePriceListPreview: 'Aperçu (5 premières lignes)',
  toastAddressRequired: 'Adresse requise',
  toastAddressDesc: "Saisissez une adresse avant d'ajouter au pipeline.",
  toastInvalidQuote: 'Devis invalide',
  toastInvalidQuoteDesc: 'Renseignez la surface du toit pour calculer le kWp.',
  newLeadDefault: 'Nouveau lead',
  withBattery: 'avec batterie',
  noBattery: 'sans batterie',
  quoteNotePrefix: 'Devis',
  /** Quote form labels (FR) */
  quoteSectionClient: 'Client & adresse',
  quoteSectionInstall: 'Installation',
  quoteSectionConsumption: 'Consommation',
  quoteProjectDetails: 'Détails du projet',
  quoteProjectDetailsDesc: 'Saisissez les informations client pour générer un devis instantané.',
  quoteClientName: 'Nom du client (optionnel — pour le pipeline)',
  quotePricingNoteTitle: 'Note tarifs',
  quotePricingNoteBody: 'Connectez votre grille tarifaire pour des marges exactes. Cette démo utilise des tarifs indicatifs (Basic 2 100 €/kWp, Premium 2 400 €/kWp, batterie +6 500 €).',
  quoteClientPlaceholder: 'ex. Jean Dupont',
  quoteFullAddress: 'Adresse complète',
  quoteAddressPlaceholder: 'ex. 24 Rue de la Gare, L-1234 Luxembourg',
  quoteRoofType: 'Type de toit',
  quoteRoofPitched: 'Toit incliné',
  quoteRoofFlat: 'Toit plat',
  quoteRoofFacade: 'Façade',
  quotePackage: 'Pack',
  quotePackageBasic: 'Basic (Q-Cells)',
  quotePackagePremium: 'Premium (SunPower)',
  quoteRoofArea: 'Surface toit (m²)',
  quoteMonthlyBill: 'Facture électricité mensuelle',
  quoteAddBattery: 'Stockage batterie (10 kWh)',
  quoteBatteryBonus: '+2 250 € Klimabonus (batterie)',
  quoteConsumptionProfile: 'Profil de consommation',
  quoteConsumptionLow: 'Faible (couple actif)',
  quoteConsumptionNormal: 'Normal (famille)',
  quoteConsumptionHigh: 'Élevé (télétravail / VE)',
  quoteSystemPerformance: 'Performance système',
  quoteSystemSize: 'Puissance',
  quotePanelsApprox: 'Environ',
  quotePanels: 'panneaux',
  quoteEstProduction: 'Production annuelle est.',
  quotePaybackPeriod: 'Retour sur investissement',
  quoteYears: 'ans',
  quoteBasedOnPrices: 'Sur la base des prix actuels',
  quoteFinancialBreakdown: 'Détail financier',
  quoteInstallationCost: "Coût d'installation",
  quoteEstimatedNetCost: 'Coût net estimé (fourchette)',
  quoteIndicativeBand: 'Bande indicative — offre ferme après visite.',
  quoteMarginAlertTitle: 'Marges faibles',
  quoteMarginAlertDesc: 'En bas de fourchette, la marge est inférieure au minimum conseillé. Vérifiez les coûts ou proposez plus haut dans la bande.',
  quoteAddToPipeline: 'Ajouter au pipeline',
  quoteGeneratePDF: 'Générer le PDF',
  quoteGenerating: 'Génération…',
  quoteSendWhatsApp: 'Envoyer par WhatsApp',
  /** Next action card */
  nextActionLabel: 'Prochaine action recommandée',
  currentStage: 'Étape actuelle',
  daysInStage: 'Jours dans l\'étape',
  markContacted: 'Marquer contact',
  openInstallChecklist: 'Ouvrir checklist installation',
  advanceStage: 'Passer à l\'étape suivante',
  /** Next action values (FR display for NextAction type) */
  nextActionCallClient: 'Appeler le client',
  nextActionScheduleVisit: 'Planifier visite',
  nextActionSendQuote: 'Envoyer devis PDF',
  nextActionSendCreos: 'Envoyer dossier CREOS',
  nextActionRequestDeposit: 'Demander acompte',
  nextActionPlanInstall: 'Planifier date installation',
  nextActionCloseProject: 'Clôturer le projet',
  /** Project details */
  notesAndActivity: 'Notes et activité',
  addNotePlaceholder: 'Ajouter une note…',
  addNoteButton: 'Ajouter',
  quickActions: 'Actions rapides',
  scheduleSiteVisit: 'Planifier visite',
  dateAndTime: 'Date et heure',
  assignedTechnician: 'Technicien assigné',
  selectTechnician: 'Choisir un technicien',
  confirmBooking: 'Confirmer',
  callClient: 'Appeler le client',
  whatsappTemplates: 'Modèles WhatsApp',
  followUpLabel: 'Relance :',
  followUpQuoteCheck: 'Relance après envoi devis',
  updateLabel: 'Mise à jour :',
  updateCreosPending: 'CREOS en cours',
  installLabel: 'Install :',
  installScheduleConfirm: 'Confirmation date installation',
  scheduledVisit: 'Visite planifiée',
  tech: 'Tech',
  systemKwp: 'Système',
  /** Install checklist page */
  installPhase: 'Phase installation',
  installChecklistTitle: 'Checklist installation',
  installManageFor: 'Gérer le déroulé d\'installation pour',
  notSet: 'Non renseigné',
  unassigned: 'Non assigné',
  visitDate: 'Date visite',
  techLead: 'Responsable tech',
  /** ChecklistSection */
  installProgress: 'Avancement installation',
  preInstallTitle: 'Avant installation',
  dayOfTitle: "Jour d'installation",
  postInstallTitle: 'Après installation',
  completeInstallButton: 'Clôturer le projet installation',
  installCompleted: 'Installation terminée',
  installSuccessTitle: 'Succès',
  installSuccessDesc: 'Projet marqué comme terminé. Le client peut être notifié pour la visite de réception.',
  /** Checklist items (FR) */
  checklistPermits: 'Permis de construire reçu',
  checklistCreos: 'Accord connexion réseau CREOS',
  checklistDeposit: 'Acompte client reçu (30 %)',
  checklistMaterials: 'Matériaux livrés en entrepôt',
  checklistTeam: 'Équipe d\'installation assignée',
  checklistSafety: 'Briefing sécurité et vérification harnais',
  checklistRoof: 'Contrôle structure toit',
  checklistMounting: 'Pose du système de fixation',
  checklistPanels: 'Pose panneaux et câblage',
  checklistInverter: 'Onduleur et batterie',
  checklistElectrical: 'Raccordement AC/DC',
  checklistTesting: 'Tests et mise en service',
  checklistCleanup: 'Nettoyage chantier et évacuation déchets',
  checklistWalkthrough: 'Visite client et config app',
  checklistDocs: 'Remise documentation finale',
  checklistPhotos: 'Photos installation uploadées',
  /** Stepper (optional display) */
  stepLead: 'Lead',
  stepVisit: 'Visite',
  stepQuote: 'Devis',
  stepCreos: 'CREOS',
  stepInstallation: 'Install',
  stepCompleted: 'Terminé',
  /** PDF */
  pdfSubsidyNote: 'Klimabonus 2026 (indicatif). Préfinancement possible : l\'installateur déduit la prime de la facture s\'il est agréé (Guichet.lu).',
  pdfValidDays: 'Valable 14 jours',
  pdfTimeline: 'Délai : 6 à 10 semaines après accord CREOS',
} as const;

export { demo };
